### ISSUE TITLE
Application Crashes When Reloading/Refreshing Data 

### ISSUE THREAD

**Issue by hmtinc** [NATHAN4/WatISpend#4]
The application seems to crash whenever you attempt to reload the application or refresh the data.

**Comment by nwoodthorpe** [comment]
Which device are you using? What are you trying to do to refresh the data?

**Comment by hmtinc** [comment]
I am using a One Plus One and it mostly crashes when I reload the app

**Comment by nwoodthorpe** [comment]
Emulated the same device and tried to recreate the bug but couldn't. If the issue persists, reopen with more information on replicating the bug.
